[alembic]
script_location = %(here)s/alembic/main
prepend_sys_path = .
path_separator = os
sqlalchemy.url =

[logs]
script_location = %(here)s/alembic/logs
prepend_sys_path = .
path_separator = os
sqlalchemy.url =
